// Catálogo de productos
const products = [
  {
    id: 1,
    name: "Polo Básico Negro",
    category: "polos",
    price: 49.90,
    oldPrice: null,
    images: ["assets/img/products/p01.webp", "assets/img/products/p01.webp", "assets/img/products/p01.webp"],
    colors: ["Negro", "Blanco", "Gris"],
    sizes: ["S", "M", "L", "XL"],
    badge: "Nuevo",
    description: "Polo básico de algodón 100%, perfecto para el día a día. Corte clásico y tela suave al tacto.",
    isNew: true,
    isOffer: false
  },
  {
    id: 2,
    name: "Polo Básico Blanco",
    category: "polos",
    price: 49.90,
    oldPrice: null,
    images: ["assets/img/products/p02.webp", "assets/img/products/p02.webp", "assets/img/products/p02.webp"],
    colors: ["Blanco", "Negro", "Gris"],
    sizes: ["S", "M", "L", "XL"],
    badge: null,
    description: "Polo básico blanco, esencial en todo guardarropa. Algodón de alta calidad.",
    isNew: false,
    isOffer: false
  },
  {
    id: 3,
    name: "Polo Cuello Navy",
    category: "polos",
    price: 89.90,
    oldPrice: 119.90,
    images: ["assets/img/products/p03.webp", "assets/img/products/p03.webp", "assets/img/products/p03.webp"],
    colors: ["Navy", "Negro", "Blanco"],
    sizes: ["S", "M", "L", "XL"],
    badge: "-25%",
    description: "Polo con cuello elegante, ideal para ocasiones semi-formales. Tejido de algodón premium.",
    isNew: false,
    isOffer: true
  },
  {
    id: 4,
    name: "Camisa Rayas Rojas",
    category: "polos",
    price: 79.90,
    oldPrice: null,
    images: ["assets/img/products/p04.webp", "assets/img/products/p04.webp", "assets/img/products/p04.webp"],
    colors: ["Rojo/Blanco", "Azul/Blanco"],
    sizes: ["S", "M", "L", "XL"],
    badge: "Nuevo",
    description: "Camisa casual de rayas, perfecta para un look fresco y moderno. 100% algodón.",
    isNew: true,
    isOffer: false
  },
  {
    id: 5,
    name: "Hoodie Gris Básico",
    category: "polos",
    price: 99.90,
    oldPrice: null,
    images: ["assets/img/products/p05.webp", "assets/img/products/p05.webp", "assets/img/products/p05.webp"],
    colors: ["Gris", "Negro", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    badge: null,
    description: "Sudadera con capucha, interior polar suave. Perfecta para el clima frío.",
    isNew: false,
    isOffer: false
  },
  {
    id: 6,
    name: "Polo Oliva con Bolsillo",
    category: "polos",
    price: 59.90,
    oldPrice: null,
    images: ["assets/img/products/p06.webp", "assets/img/products/p06.webp", "assets/img/products/p06.webp"],
    colors: ["Oliva", "Mostaza", "Terracota"],
    sizes: ["S", "M", "L", "XL"],
    badge: "Nuevo",
    description: "Polo de algodón con bolsillo frontal, detalle casual y funcional.",
    isNew: true,
    isOffer: false
  },
  {
    id: 7,
    name: "Polo Vinotinto Cuello V",
    category: "polos",
    price: 54.90,
    oldPrice: null,
    images: ["assets/img/products/p07.webp", "assets/img/products/p07.webp", "assets/img/products/p07.webp"],
    colors: ["Vinotinto", "Negro", "Gris"],
    sizes: ["S", "M", "L", "XL"],
    badge: null,
    description: "Polo con cuello en V, elegante y versátil. Algodón suave de primera calidad.",
    isNew: false,
    isOffer: false
  },
  {
    id: 8,
    name: "Polo Gráfico Mostaza",
    category: "polos",
    price: 69.90,
    oldPrice: 89.90,
    images: ["assets/img/products/p08.webp", "assets/img/products/p08.webp", "assets/img/products/p08.webp"],
    colors: ["Mostaza", "Blanco", "Negro"],
    sizes: ["S", "M", "L", "XL"],
    badge: "-22%",
    description: "Polo con estampado gráfico moderno, diseño exclusivo que marca tendencia.",
    isNew: false,
    isOffer: true
  },
  {
    id: 9,
    name: "Jean Clásico Azul",
    category: "jeans",
    price: 129.90,
    oldPrice: null,
    images: ["assets/img/products/p09.webp", "assets/img/products/p09.webp", "assets/img/products/p09.webp"],
    colors: ["Azul claro", "Azul oscuro"],
    sizes: ["28", "30", "32", "34", "36"],
    badge: null,
    description: "Jean clásico de corte regular, denim resistente y cómodo para uso diario.",
    isNew: false,
    isOffer: false
  },
  {
    id: 10,
    name: "Jean Negro Skinny",
    category: "jeans",
    price: 139.90,
    oldPrice: 179.90,
    images: ["assets/img/products/p10.webp", "assets/img/products/p10.webp", "assets/img/products/p10.webp"],
    colors: ["Negro", "Gris oscuro"],
    sizes: ["28", "30", "32", "34", "36"],
    badge: "-22%",
    description: "Jean negro ajustado, corte skinny moderno. Denim elástico para mayor comodidad.",
    isNew: false,
    isOffer: true
  },
  {
    id: 11,
    name: "Jean Desgastado Claro",
    category: "jeans",
    price: 149.90,
    oldPrice: null,
    images: ["assets/img/products/p11.webp", "assets/img/products/p11.webp", "assets/img/products/p11.webp"],
    colors: ["Azul claro"],
    sizes: ["28", "30", "32", "34", "36"],
    badge: "Nuevo",
    description: "Jean con desgaste auténtico, estilo urbano y actual. Acabados rasgados.",
    isNew: true,
    isOffer: false
  },
  {
    id: 12,
    name: "Chino Khaki",
    category: "jeans",
    price: 119.90,
    oldPrice: null,
    images: ["assets/img/products/p12.webp", "assets/img/products/p12.webp", "assets/img/products/p12.webp"],
    colors: ["Khaki", "Navy", "Gris"],
    sizes: ["28", "30", "32", "34", "36"],
    badge: null,
    description: "Pantalón chino elegante, ideal para ocasiones casuales o formales.",
    isNew: false,
    isOffer: false
  },
  {
    id: 13,
    name: "Jogger Gris Deportivo",
    category: "jeans",
    price: 89.90,
    oldPrice: null,
    images: ["assets/img/products/p13.webp", "assets/img/products/p13.webp", "assets/img/products/p13.webp"],
    colors: ["Gris", "Negro", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    badge: null,
    description: "Pantalón jogger con puños elásticos, perfecto para el gym o uso casual.",
    isNew: false,
    isOffer: false
  },
  {
    id: 14,
    name: "Cargo Beige",
    category: "jeans",
    price: 139.90,
    oldPrice: null,
    images: ["assets/img/products/p14.webp", "assets/img/products/p14.webp", "assets/img/products/p14.webp"],
    colors: ["Beige", "Verde militar", "Negro"],
    sizes: ["28", "30", "32", "34", "36"],
    badge: "Nuevo",
    description: "Pantalón cargo con múltiples bolsillos, estilo utilitario y funcional.",
    isNew: true,
    isOffer: false
  },
  {
    id: 15,
    name: "Vestido Negro Elegante",
    category: "vestidos",
    price: 179.90,
    oldPrice: null,
    images: ["assets/img/products/p15.webp", "assets/img/products/p15.webp", "assets/img/products/p15.webp"],
    colors: ["Negro"],  
    sizes: ["XS", "S", "M", "L"],
    badge: null,
    description: "Vestido de cóctel elegante, tela fluida y caída perfecta para eventos especiales.",
    isNew: false,
    isOffer: false
  },
  // Productos 16-30 con placeholder temporal (se pueden actualizar las imágenes después)
  {
    id: 16,
    name: "Vestido Floral Verano",
    category: "vestidos",
    price: 149.90,
    oldPrice: 189.90,
    images: ["assets/img/products/p15.webp", "assets/img/products/p15.webp", "assets/img/products/p15.webp"],
    colors: ["Multicolor", "Blanco"],
    sizes: ["XS", "S", "M", "L"],
    badge: "-21%",
    description: "Vestido floral ligero, perfecto para días soleados. Tela respirable y fresca.",
    isNew: false,
    isOffer: true
  },
  {
    id: 17,
    name: "Vestido Rojo Maxi",
    category: "vestidos",
    price: 199.90,
    oldPrice: null,
    images: ["assets/img/products/p15.webp", "assets/img/products/p15.webp", "assets/img/products/p15.webp"],
    colors: ["Rojo", "Negro"],
    sizes: ["XS", "S", "M", "L"],
    badge: "Nuevo",
    description: "Vestido largo de noche, diseño sofisticado para ocasiones especiales.",
    isNew: true,
    isOffer: false
  },
  {
    id: 18,
    name: "Vestido Camisero Blanco",
    category: "vestidos",
    price: 129.90,
    oldPrice: null,
    images: ["assets/img/products/p15.webp", "assets/img/products/p15.webp", "assets/img/products/p15.webp"],
    colors: ["Blanco", "Beige"],
    sizes: ["XS", "S", "M", "L"],
    badge: null,
    description: "Vestido tipo camisa, versátil y cómodo para uso diario o trabajo.",
    isNew: false,
    isOffer: false
  },
  {
    id: 19,
    name: "Vestido Denim Casual",
    category: "vestidos",
    price: 139.90,
    oldPrice: null,
    images: ["assets/img/products/p15.webp", "assets/img/products/p15.webp", "assets/img/products/p15.webp"],
    colors: ["Azul denim"],
    sizes: ["XS", "S", "M", "L"],
    badge: "Nuevo",
    description: "Vestido de mezclilla con botones frontales, estilo casual y moderno.",
    isNew: true,
    isOffer: false
  },
  {
    id: 20,
    name: "Zapatillas Blancas Cuero",
    category: "zapatillas",
    price: 169.90,
    oldPrice: null,
    images: ["assets/img/products/p01.webp", "assets/img/products/p01.webp", "assets/img/products/p01.webp"],
    colors: ["Blanco", "Blanco/Negro"],
    sizes: ["37", "38", "39", "40", "41", "42"],
    badge: null,
    description: "Zapatillas blancas clásicas de cuero, suela de goma antideslizante.",
    isNew: false,
    isOffer: false
  },
  {
    id: 21,
    name: "Zapatillas Lona Negras",
    category: "zapatillas",
    price: 119.90,
    oldPrice: 149.90,
    images: ["assets/img/products/p01.webp", "assets/img/products/p01.webp", "assets/img/products/p01.webp"],
    colors: ["Negro", "Blanco", "Azul"],
    sizes: ["37", "38", "39", "40", "41", "42"],
    badge: "-20%",
    description: "Zapatillas de lona casuales, cómodas y transpirables para el día a día.",
    isNew: false,
    isOffer: true
  },
  {
    id: 22,
    name: "Zapatillas Running Sport",
    category: "zapatillas",
    price: 199.90,
    oldPrice: null,
    images: ["assets/img/products/p01.webp", "assets/img/products/p01.webp", "assets/img/products/p01.webp"],
    colors: ["Negro/Rojo", "Gris/Azul"],
    sizes: ["37", "38", "39", "40", "41", "42", "43"],
    badge: "Nuevo",
    description: "Zapatillas deportivas para running, suela con amortiguación superior.",
    isNew: true,
    isOffer: false
  },
  {
    id: 23,
    name: "Botines Cuero Marrón",
    category: "zapatillas",
    price: 249.90,
    oldPrice: null,
    images: ["assets/img/products/p01.webp", "assets/img/products/p01.webp", "assets/img/products/p01.webp"],
    colors: ["Marrón", "Negro"],
    sizes: ["37", "38", "39", "40", "41", "42"],
    badge: null,
    description: "Botines de cuero genuino, elegantes y resistentes para temporada fría.",
    isNew: false,
    isOffer: false
  },
  {
    id: 24,
    name: "Slip-On Navy Casual",
    category: "zapatillas",
    price: 109.90,
    oldPrice: null,
    images: ["assets/img/products/p01.webp", "assets/img/products/p01.webp", "assets/img/products/p01.webp"],
    colors: ["Navy", "Gris", "Beige"],
    sizes: ["37", "38", "39", "40", "41", "42"],
    badge: null,
    description: "Zapatos sin cordones, fáciles de poner y perfectos para un look casual.",
    isNew: false,
    isOffer: false
  },
  {
    id: 25,
    name: "Zapatillas Bota Alta",
    category: "zapatillas",
    price: 179.90,
    oldPrice: 219.90,
    images: ["assets/img/products/p01.webp", "assets/img/products/p01.webp", "assets/img/products/p01.webp"],
    colors: ["Blanco", "Negro"],
    sizes: ["37", "38", "39", "40", "41", "42"],
    badge: "-18%",
    description: "Zapatillas de caña alta estilo urbano, diseño moderno y cómodo.",
    isNew: false,
    isOffer: true
  },
  {
    id: 26,
    name: "Correa Cuero Negro",
    category: "accesorios",
    price: 59.90,
    oldPrice: null,
    images: ["assets/img/products/p02.webp", "assets/img/products/p02.webp", "assets/img/products/p02.webp"],
    colors: ["Negro", "Marrón"],
    sizes: ["Única"],
    badge: null,
    description: "Correa de cuero genuino con hebilla metálica, ajustable y duradera.",
    isNew: false,
    isOffer: false
  },
  {
    id: 27,
    name: "Mochila Cuero Marrón",
    category: "accesorios",
    price: 229.90,
    oldPrice: null,
    images: ["assets/img/products/p02.webp", "assets/img/products/p02.webp", "assets/img/products/p02.webp"],
    colors: ["Marrón", "Negro"],
    sizes: ["Única"],
    badge: "Nuevo",
    description: "Mochila de cuero con compartimentos organizadores, ideal para laptop.",
    isNew: true,
    isOffer: false
  },
  {
    id: 28,
    name: "Bolso Tote Beige",
    category: "accesorios",
    price: 89.90,
    oldPrice: null,
    images: ["assets/img/products/p02.webp", "assets/img/products/p02.webp", "assets/img/products/p02.webp"],
    colors: ["Beige", "Negro", "Gris"],
    sizes: ["Única"],
    badge: null,
    description: "Bolso tote de lona resistente, espacioso y perfecto para compras o playa.",
    isNew: false,
    isOffer: false
  },
  {
    id: 29,
    name: "Gorra Negra Ajustable",
    category: "accesorios",
    price: 49.90,
    oldPrice: 69.90,
    images: ["assets/img/products/p02.webp", "assets/img/products/p02.webp", "assets/img/products/p02.webp"],
    colors: ["Negro", "Navy", "Gris"],
    sizes: ["Única"],
    badge: "-29%",
    description: "Gorra de béisbol con cierre ajustable, protección solar y estilo urbano.",
    isNew: false,
    isOffer: true
  },
  {
    id: 30,
    name: "Lentes de Sol Aviador",
    category: "accesorios",
    price: 79.90,
    oldPrice: null,
    images: ["assets/img/products/p02.webp", "assets/img/products/p02.webp", "assets/img/products/p02.webp"],
    colors: ["Dorado", "Plateado", "Negro"],
    sizes: ["Única"],
    badge: "Nuevo",
    description: "Lentes de sol estilo aviador con protección UV400, lentes polarizados.",
    isNew: true,
    isOffer: false
  }
];

// Datos de testimonios
const testimonials = [
  {
    id: 1,
    name: "María González",
    image: "assets/img/testimonials/t01.webp",
    rating: 5,
    text: "Excelente calidad y los jeans me quedaron perfectos. El envío fue muy rápido.",
    date: "Hace 2 días"
  },
  {
    id: 2,
    name: "Carlos Mendoza",
    image: "assets/img/testimonials/t02.webp",
    rating: 5,
    text: "Las zapatillas son tal cual la foto, muy cómodas. Totalmente recomendado.",
    date: "Hace 1 semana"
  },
  {
    id: 3,
    name: "Ana Ríos",
    image: "assets/img/testimonials/t03.webp",
    rating: 5,
    text: "Me encantó el vestido negro, la tela es de muy buena calidad. Volveré a comprar.",
    date: "Hace 2 semanas"
  },
  {
    id: 4,
    name: "Jorge Paredes",
    image: "assets/img/testimonials/t04.webp",
    rating: 4,
    text: "Buenos precios y variedad. Los polos son básicos pero de calidad.",
    date: "Hace 3 semanas"
  },
  {
    id: 5,
    name: "Lucía Torres",
    image: "assets/img/testimonials/t05.webp",
    rating: 5,
    text: "Atención rápida por WhatsApp. El cambio de talla fue muy fácil.",
    date: "Hace 1 mes"
  },
  {
    id: 6,
    name: "Pedro Sánchez",
    image: "assets/img/testimonials/t06.webp",
    rating: 5,
    text: "La mochila de cuero es hermosa, justo lo que buscaba. Envío a provincia sin problemas.",
    date: "Hace 1 mes"
  }
];

// Configuración de contacto
const contactConfig = {
  whatsapp: "+51987654321",
  instagram: "@tiendaropa_demo",
  email: "contacto@tiendaropa.com",
  address: "Av. Principal 123, Lima, Perú",
  hours: "Lun - Sáb: 10:00 AM - 8:00 PM"
};
